spring:
  h2:
    console:
      enabled: true
      path: /console
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 'my_google_client_id'
            client-secret: 'my_google_client_secret'
          facebook:
            client-id: 'my_facebook_client_id'
            client-secret: 'my_facebook_client_secret'

  datasource:
    url: jdbc:h2:tcp://localhost/~/fourartist
    username: hong
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
          #show_sql: true
        format_sql: true
custom:
  oauth2:
    kakao:
      client-id: 'my_kakao_client_id'
      client-secret: 'my_kakao_client_secret'
    naver:
      client-id: 'my_naver_client_id'
      client-secret: 'my_naver_client_secret'
logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: DEBUG
  org.springframework.web: DEBUG


# org.hibernate.type: trace
